### ISSUE TITLE
theBot.py

### ISSUE THREAD

**Issue by SSwiftGamer440** [SSwiftGamer440/HackersPy#3] opened 2020-01-08 20:35 UTC
theBot.py issues ModuleNotFoundError for requests

**Comment by molchu** [comment] 2020-01-09 22:06
You need to install requests by typing the following command in your CMD:
pip install requests
Closed as this is not a bug but rather the collaborator does not have the library installed on their device, hence "Module Not Found"

**Closed by molchu** 2020-01-09 22:06 UTC
Labels: bug
